### ISSUE TITLE
Error occur when execute GmSSL#getVersion()

### ISSUE THREAD

**Issue by fangjinuo** [gitveio/gmssl-dev#1]
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.github.gitveio.GmSSL.getVersions()[Ljava/lang/String;
	at com.github.gitveio.GmSSL.getVersions(Native Method)

**Comment by fangjinuo** [comment]
final GmSSL gmssl = new GmSSL();
        String[] versions = gmssl.getVersions();
        if (versions != null) {
            for (String v : versions) {
                System.out.println(v);
            }
        } else {
            System.out.println("no versions");
        }

**Comment by gitveio** [comment]
sorrry, fixed now. modify version to 1.1.1
